### PR TITLE
Fix overlapping fullscreen editor

### PR DESCRIPTION
**Pull request by deepsweet**

### CODE REVIEW

**Comment by Deschtex** [comment]
LGTM. @pirelenito?

**Review by Deschtex — APPROVED** [review]

**Comment by pirelenito** [comment]
How does it looks in comparison? Can you provide screenshots? Before/after?

**Comment by deepsweet** [comment]
before:
before

after:
after

so now it's possible to click on content.

**Comment by pirelenito** [comment]
Released https://github.com/batata-frita/lekplats/releases/tag/v0.3.0

**Pull request merged**
